Remove yubiswitch from Brewfile
It appears that yubiswitch can no longer be installed via homebrew:

Error: No available Cask for yubiswitch
Error: nothing to install
Installing yubiswitch has failed!
Homebrew Bundle failed! 1 Brewfile dependencies failed to install.